kpse.set_program_name("luatex")

local function print_help()
  io.write([[
SpanishCards JSON-to-TeX converter

Usage:
  texlua scripts/json-to-tex.lua --input FILE --output FILE [options]

Required:
  --input FILE       UTF-8 JSON vocabulary file
  --output FILE      Destination TeX file

Options:
  --format FORMAT    fragment or document (default: fragment)
  --view VIEW        cards or table (default: cards)
  --help             Show this help

Examples:
  texlua scripts/json-to-tex.lua \
    --input data/example.json \
    --output generated/example.tex \
    --format fragment

  texlua scripts/json-to-tex.lua \
    --input data/example.json \
    --output generated/example-document.tex \
    --format document \
    --view table
]])
end

local function fail(message, exit_code)
  io.stderr:write("json-to-tex: " .. message .. "\n")
  os.exit(exit_code or 1)
end

local function parse_arguments(arguments)
  local options = {
    format = "fragment",
    view = "cards",
  }
  local known_options = {
    input = true,
    output = true,
    format = true,
    view = true,
  }
  local index = 1

  while index <= #arguments do
    local argument = arguments[index]
    if argument == "--help" then
      options.help = true
      index = index + 1
    else
      local inline_key, inline_value = argument:match("^%-%-([%w-]+)=(.*)$")
      if inline_key then
        if not known_options[inline_key] then
          fail("unknown option '--" .. inline_key .. "'", 2)
        end
        options[inline_key] = inline_value
        index = index + 1
      else
        local key = argument:match("^%-%-([%w-]+)$")
        if not key or not known_options[key] then
          fail("unknown option '" .. argument .. "'", 2)
        end
        local value = arguments[index + 1]
        if not value or value:match("^%-%-") then
          fail("option '--" .. key .. "' requires a value", 2)
        end
        options[key] = value
        index = index + 2
      end
    end
  end

  return options
end

local function script_project_root()
  local script_path = (arg[0] or "scripts/json-to-tex.lua"):gsub("\\", "/")
  local script_directory = script_path:match("^(.*)/[^/]+$") or "."
  return script_directory:match("^(.*)/scripts$") or "."
end

local function load_data_module()
  local project_root = script_project_root()
  local module_path = kpse.find_file("spanishcards-data.lua")
    or (project_root .. "/spanishcards-data.lua")
  local handle = io.open(module_path, "rb")
  if not handle then
    fail("cannot locate spanishcards-data.lua")
  end
  handle:close()

  local load_ok, module_or_error = pcall(dofile, module_path)
  if not load_ok then
    fail("cannot load data module: " .. module_or_error)
  end
  return module_or_error
end

local function directory_name(path)
  local normalized = path:gsub("\\", "/")
  return normalized:match("^(.*)/[^/]*$") or "."
end

local function ensure_directory(path)
  if path == "" or path == "." then
    return true
  end

  local mode = lfs.attributes(path, "mode")
  if mode == "directory" then
    return true
  elseif mode then
    return nil, "path exists and is not a directory: " .. path
  end

  local parent = directory_name(path)
  if parent ~= path then
    local parent_ok, parent_error = ensure_directory(parent)
    if not parent_ok then
      return nil, parent_error
    end
  end

  local created, create_error = lfs.mkdir(path)
  if not created and lfs.attributes(path, "mode") ~= "directory" then
    return nil, create_error or ("cannot create directory: " .. path)
  end
  return true
end

local function write_atomic(path, content)
  local output_directory = directory_name(path)
  local directory_ok, directory_error = ensure_directory(output_directory)
  if not directory_ok then
    return nil, directory_error
  end

  local temporary_path = path .. ".tmp"
  local handle, open_error = io.open(temporary_path, "wb")
  if not handle then
    return nil, open_error or ("cannot open temporary file: " .. temporary_path)
  end

  local write_ok, write_error = handle:write(content)
  local close_ok, close_error = handle:close()
  if not write_ok or not close_ok then
    os.remove(temporary_path)
    return nil, write_error or close_error or "cannot finish writing output"
  end

  local renamed, rename_error = os.rename(temporary_path, path)
  if not renamed then
    os.remove(path)
    renamed, rename_error = os.rename(temporary_path, path)
  end
  if not renamed then
    os.remove(temporary_path)
    return nil, rename_error or ("cannot replace output: " .. path)
  end

  return true
end

local function generated_header(source)
  local safe_source = source:gsub("[\r\n]", " ")
  return table.concat({
    "% Generated by SpanishCards. Do not edit manually.",
    "% Source: " .. safe_source,
    "",
  }, "\n")
end

local function render_fragment(entries, source)
  local body = generated_header(source)
  if entries ~= "" then
    body = body .. entries .. "\n"
  end
  return body
end

local function render_document(entries, source, view)
  local print_command = view == "table"
    and "\\PrintVocabularyTable"
    or "\\PrintVocabularyCards"
  local parts = {
    generated_header(source),
    "\\documentclass{spanishcards}",
    "",
    "\\begin{document}",
    "",
  }

  if entries ~= "" then
    parts[#parts + 1] = entries
    parts[#parts + 1] = ""
  end

  parts[#parts + 1] = print_command
  parts[#parts + 1] = ""
  parts[#parts + 1] = "\\end{document}"
  parts[#parts + 1] = ""
  return table.concat(parts, "\n")
end

local options = parse_arguments(arg)
if options.help then
  print_help()
  os.exit(0)
end

if not options.input or options.input == "" then
  fail("--input is required", 2)
end
if not options.output or options.output == "" then
  fail("--output is required", 2)
end
if options.format ~= "fragment" and options.format ~= "document" then
  fail("--format must be 'fragment' or 'document'", 2)
end
if options.view ~= "cards" and options.view ~= "table" then
  fail("--view must be 'cards' or 'table'", 2)
end

local data_module = load_data_module()
local records, read_error = data_module.read_json_records(options.input)
if not records then
  fail(read_error)
end

local entries = data_module.records_to_latex(records, options.input)
local output
if options.format == "document" then
  output = render_document(entries, options.input, options.view)
else
  output = render_fragment(entries, options.input)
end

local write_ok, write_error = write_atomic(options.output, output)
if not write_ok then
  fail("cannot write '" .. options.output .. "': " .. write_error)
end

io.write(string.format(
  "Generated %s (%s, %s view)\n",
  options.output,
  options.format,
  options.view
))
